### ISSUE TITLE
Project initialisation

### ISSUE THREAD

**Issue by leroyvn** [leroyvn/copier-pdm#1]
This issue contains the work breakdown for the initialisation of this project.

### Basic setup

- [x] Add `copier.yml` based on existing templates
- [x] Add `pyproject.toml` template

### Tasks

- [x] Implement task automation with [duty](https://github.com/pawamoy/duty)
- [x] Add makefile
- [x] Add formatting tools: autoflake (for unused import removal), isort, Black
- [ ] Add checks: mypy (and typing), flake8, formatting
- [x] Add testing framework: pytest (with [xdoctest](https://github.com/Erotemic/xdoctest), [coverage](https://coverage.readthedocs.io/en/6.2/)), [nox](https://nox.thea.codes/en/stable/)
- [ ] Add pre-commit support

### Testing

- [x] Configure pytest and add test directory

### Documentation

- [x] Add documentation framework: Sphinx with [Furo theme](https://pradyunsg.me/furo/), [Numpy docstring format](http://numpydoc.readthedocs.io/)
- [ ] Add README badges
- [ ] Add changelog management: generate from commits using [git-changelog](https://github.com/pawamoy/git-changelog)
- [ ] Add developer documentation

### Continuous integration

- [x] Configure GitHub Actions
- [ ] Configure Read the Docs

### Virtual environment support

- [x] Document option to use an env manager
- [ ] Add Conda dependency lock using [conda-lock](https://github.com/conda-incubator/conda-lock) (supports PEP 621 AFAIK, can also lock reliably Pip deps using the Poetry solver)

### GitHub project

- [ ] Add tags
